//===-- MiniRvccSubtarget.h - Define Subtarget for the MiniRvcc -------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file declares the MiniRvcc specific subclass of TargetSubtargetInfo.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_LIB_TARGET_MINIRVCC_MINIRVCCSUBTARGET_H
#define LLVM_LIB_TARGET_MINIRVCC_MINIRVCCSUBTARGET_H

//#include "MCTargetDesc/RISCVBaseInfo.h"
#include "MiniRvccFrameLowering.h"
#include "MiniRvccISelLowering.h"
#include "MiniRvccInstrInfo.h"
#include "llvm/CodeGen/GlobalISel/CallLowering.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelector.h"
#include "llvm/CodeGen/GlobalISel/LegalizerInfo.h"
#include "llvm/CodeGen/RegisterBankInfo.h"
#include "llvm/CodeGen/SelectionDAGTargetInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/Target/TargetMachine.h"

#define GET_SUBTARGETINFO_HEADER
#include "MiniRvccGenSubtargetInfo.inc"

namespace llvm {
class StringRef;

class MiniRvccSubtarget : public MiniRvccGenSubtargetInfo {
private:
   virtual void anchor();
   MVT XLenVT = MVT::i32;

   uint8_t MaxInterleaveFactor = 2;
   MiniRvccABI::ABI TargetABI = MiniRvccABI::ABI_Unknown;
   BitVector UserReservedRegister;
   MiniRvccFrameLowering FrameLowering;
   MiniRvccInstrInfo InstrInfo;
   MiniRvccRegisterInfo RegInfo;
   MiniRvccTargetLowering TLInfo;
   SelectionDAGTargetInfo TSInfo;

   /// Initializes using the passed in CPU and feature strings so that we can
   /// use initializer lists for subtarget initialization.
   MiniRvccSubtarget &initializeSubtargetDependencies(const Triple &TT,
                                                      StringRef CPU,
                                                      StringRef TuneCPU,
                                                      StringRef FS,
                                                      StringRef ABIName);

public:
   // Initializes the data members to match that of the specified triple.
   MiniRvccSubtarget(const Triple &TT, StringRef CPU, StringRef TuneCPU,
                     StringRef FS, StringRef ABIName, const TargetMachine &TM);

   // Parses features string setting specified subtarget options. The
   // definition of this function is auto-generated by tblgen.
   void ParseSubtargetFeatures(StringRef CPU, StringRef TuneCPU, StringRef FS);

   const MiniRvccFrameLowering *getFrameLowering() const override {
      return &FrameLowering;
   }
   const MiniRvccInstrInfo *getInstrInfo() const override {
      return &InstrInfo; 
   }
   const MiniRvccRegisterInfo *getRegisterInfo() const override {
      return &RegInfo;
   }
   const MiniRvccTargetLowering *getTargetLowering() const override {
      return &TLInfo;
   }
   const SelectionDAGTargetInfo *getSelectionDAGInfo() const override {
      return &TSInfo;
   }

#if 0
   bool enableMachineScheduler() const override { return true; }
#endif

   MVT getXLenVT() const { return XLenVT; }
   unsigned getXLen() const { return XLen; }

#if 0
   MiniRvccABI::ABI getTargetABI() const { return TargetABI; }
   bool isRegisterReservedByUser(Register i) const {
      assert(i < MiniRvcc::NUM_TARGET_REGS && "Register out of range");
      return UserReservedRegister[i];
   }
#endif

protected:
   // GlobalISel related APIs.
   std::unique_ptr<CallLowering> CallLoweringInfo;
   std::unique_ptr<InstructionSelector> InstSelector;
   std::unique_ptr<LegalizerInfo> Legalizer;
   std::unique_ptr<RegisterBankInfo> RegBankInfo;

public:
   const CallLowering *getCallLowering() const override;
   InstructionSelector *getInstructionSelector() const override;
   const LegalizerInfo *getLegalizerInfo() const override;
   const RegisterBankInfo *getRegBankInfo() const override;

   bool useConstantPoolForLargeInts() const;

   // Maximum cost used for building integers, integers will be put into constant
   // pool if exceeded.
   unsigned getMaxBuildIntsCost() const;

   bool enableSubRegLiveness() const override;

   void getPostRAMutations(std::vector<std::unique_ptr<ScheduleDAGMutation>>
                              &Mutations) const override;
};
} // End llvm namespace

#endif